spring.datasource.url=jdbc:postgresql://localhost:5432/iam_db
spring.datasource.username=postgres
spring.datasource.password=Chandu@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=chandu
spring.security.user.password=0001
logging.level.org.springframework.security=DEBUG